WIP: Added support for PULP hardware loop
Added two relocations REL12 and RELU5, the PULP INSN_CLASSes, the MATCH and MASKs and the HWLP instructions.
Still require:
	* More relocations
	* More instructions
	* Most functions in ld/emultempl/riscvelf.em (May not be necessary)
	  - eg MergeChipInfo

Current problem: Unable to build due to:
	* elfnn-riscv.c:1420:5: error: duplicate case value
	* elfnn-riscv.c:1331:5: note: previously used here
	* elfnn-riscv.c:1766:9: error: duplicate case value
	* elfnn-riscv.c:1761:2: note: previously used here

bfd/ChangeLog:
        * elfnn-riscv.c: Added relocations for PULP hardware loop.
        * elfxx-riscv.c: Likewise.
gas/ChangeLog:
        * config/tc-riscv.c: Added initial PULP support and instruction
        classes.
        * config/tc-riscv.h: Likewise.
include/ChangeLog:
        * elf/riscv.h: Added initial PULP support.
        * opcode/riscv-opc.h: Likewise.
        * opcode/riscv.h: Likewise.
ld/ChangeLog:
        * emultempl/riscvelf.em: Added initial PULP support.
opcodes/ChangeLog:
        * riscv-opc.c (riscv_opcodes): Added PULP hardware loop instructions.